### PR TITLE
Fix potential memory leaks/unhandled errors

### LINKED ISSUE #4: [bug] Segfault during long break
Reproducing:
0. Install with go install @latest
1. start pomotui, set short break to 5', long break to 20', 4 25-minute session cycle
2. When a long break is entered, stop, then continue
See the error:
```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:371 +0x95
panic({0x59a880, 0x6fda40})
        /usr/lib/go/src/runtime/panic.go:890 +0x262
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc0001280b0)
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:540 +0x1276
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:547
main.main()
        /home/me/go/pkg/mod/github.com/charlieroth/pomotui@v0.0.0-20220806094103-8ff7857b4e20/main.go:13 +0x8a
```
Judging from where the error occurs, this might be an upstream issue with bubbletea, but unlikely. 

On a side note, I'd love to see the support for skipping breaks or work sessions implemented, as well as restarting the counter (can contribute my time for that in near future as well).

Go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/me/go/bin"
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY="github.com/italistdev"
GONOSUMDB="github.com/italistdev"
GOOS="linux"
GOPATH="/home/me/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build300346513=/tmp/go-build -gno-record-gcc-switches"
```
other relevant env vars:
```
$TERM: screen-256color (Alacritty with tmux on Wayland)
$SHELL: zsh
$OSTYPE: linux-musl
kernel version: 5.15.95-0-lts
```
I also think that the issue might be related to cgo having compatibility issues with musl, though given that go and alpine go kinda hand in hand in docker containers I also doubt it. I faced this issue way more often with rust crates that utilize the libc crate, this was also the reason I chose this program over rusty krab manager.

### PR DESCRIPTION
**Pull request by mjholub**
Ok so generally I've tried to find a fix for https://github.com/charlieroth/pomotui/issues/4, but it is kind of an edge case, so I'd need to create some tests that will emulate such edge cases. For this reason, I've converted some functions into methods, so that I can define a relevant interface, which I've used to generate mocks. I'll open a PR with the tests at a later time. 

Most changes are cosmetic, but I caught [one potential race condition ](https://github.com/154pinkchairs/pomotui/blob/973b46e63de334885ca5041aebe879d71ba4fcbc/model/view.go#L67), one or two unclosed files, a few unchecked errors. Also when it comes to error handling I think a better idea would be to have some structured logger like zerolog or send notifications when e.g. sound cannot be played or other non-critical errors occur and then the app would retry (there is a library made by avast for that) or use some fallback instead of calling panic.

I've also updated the dependencies in case it's an upstream bug.

Btw it would be great to have the possibility to set the source and the volume of the bell, because I often miss it.

### CODE REVIEW

**Comment by charlieroth** [comment]
Thank you for the effort. Will take a closer look this weekend 🙂

**Review by charlieroth — COMMENTED** [review]
Thank you for the contribution. From a code review perspective every looks good 👍 I am giving program a quick QA run and if the segfault issue doesn't occur then I will merge this

Also if you want to contribute more in the future I will gladly add you as a collaborator to this project so you can freely push changes you want to see. Just let me know

**Comment by charlieroth** [comment]
Followed your instructions in the #4 and received the following error:

```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/Users/charlie/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x95
panic({0x10012d8e0, 0x10025ca70})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0000ea160, {0x100186298?, 0xc0001de000?}, 0x100126080?)
	/Users/charlie/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:345 +0x639
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000ea160)
	/Users/charlie/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x7fd
github.com/charmbracelet/bubbletea.(*Program).Start(...)
	/Users/charlie/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:507
main.main()
	/Users/charlie/github.com/154pinkchairs/pomotui/main.go:14 +0x70
```

**Comment by mjholub** [comment]
ok so I've managed to additionally do some changes that may be of help, but tbh running this program through valgrind mostly shows some issues with pipewire and bubbletea. One possible check I think that might help would be making it so that whet decodeSound returns an error just log that but don't cause the program to panic. For now I've just wrapped the sound playing function in an anonymous goroutine as to ensure it doesn't fire up before the sound is decoded. I'll dogfood the changes through the day and see if it helps.

**Review by charlieroth — APPROVED** [review]

**Pull request merged**
